run:
  timeout: 5m

output:
  formats: 
  - format: "colored-line-number"
  print-issued-lines: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
  exclude-use-default: false
  exclude-rules:
    - path: ".*_test\\.go$"
      linters:
        - errcheck
    - path: ".*\\.pb\\.go$"
      linters:
        - staticcheck

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive
    - goconst
    - gocyclo
    - gosimple
    - copyloopvar
    - typecheck
    - ineffassign
    - asasalint
    - bodyclose
    - prealloc
    - gosec
  disable:
    - nakedret
    - forcetypeassert
    - funlen
    - exportloopref

linters-settings:
  revive:
    ignore-generated-header: true
    severity: warning
    rules:
      - name: indent-error-flow
        severity: error
      - name: unexported-naming
        severity: warning

  gocyclo:
    min-complexity: 15

  gosec:
    excludes:
      - G104
    severity: "medium"

  goconst:
    min-len: 3
    min-occurrences: 2

  errcheck:
    exclude-functions:
      - "render\\..*"       
      - "r\\.Body\\.Close"  
      - "sqlDB\\.Close"     
      - "tx\\.Rollback"     

  prealloc:
    simple: true

  # bodyclose:
    # require-noerror: true

  staticcheck:
    checks:
      - SA1019  
      - S1009
