services:
  # auth:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile

  redis:
    image: redis:7.4.1
    container_name: redis
    environment:
      - REDIS_PASSWORD=secret-password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    networks:
      - e-commerce-network

  postgres:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - e-commerce-network

volumes:
  redis_data:
    driver: local
  pg_data:
    driver: local

networks:
  e-commerce-network:
    name: e-commerce-network
    driver: bridge