ENV: "local"

http_server:
  host: "localhost"
  port: "8080"
  idle_timeout: 4s

database:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  db_name: "postgres"

cache:
  address: "localhost:6379"
  password: "password"
  db: 0
