ENV: "local"

http_server:
  host: "localhost"
  port: "8080"
  idle_timeout: 4s

postgres:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  db_name: "postgres"
  max_conns: 100

redis:
  address: "localhost:6379"
  password: "secret-password"
  db: 0
