ENV: "local"

app:
  prefix: "USERS_"


http_server:
  host: "localhost"
  port: "8080"
  idle_timeout: 4s

postgres:
  user: "postgres"
  password: "postgres"
  host: "localhost"
  port: "5432"
  db_name: "postgres"
  max_conns: 100

redis:
  address: "localhost:6379"
  password: "secret-password"
  db: 0

tokens:
  secret: "secret-key"
  access_ttl: 900s # 15 mins
  refresh_ttl: 900s # 15 mins