name: CI/CD Pipeline

on:
  push:
    branches:
      - main       # Срабатывает на пуш в main
    tags:
      - 'v*'       # Срабатывает на пуш тегов версии
  pull_request:
    branches:
      - main       # Срабатывает на PR в main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Run linter
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.62.2

    - name: Run tests
      run: go test -v ./...

  containerize:
    needs: lint-and-test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') || 
      github.event_name == 'pull_request' && startsWith(github.head_ref, 'v')
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build and push container
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          cvbnmd/e-commerce-users-service:latest
          cvbnmd/e-commerce-users-service:${{ github.ref_name }}
        context: .
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
