name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branches ]

jobs:
  buid:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Containerize and push
      uses: docker/build-push-action@v6
      with:
        image: cvbnmd/e-commerce-users-service
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
